### ISSUE TITLE
test/close.js crash error

### ISSUE THREAD

**Issue by pfrazee** [ssbc/secret-stack#2]
What's going on with `test/close.js` ? It crashes when run, isnt imported by any other files, and doesnt seem to have any tests in it.

**Comment by dominictarr** [comment]
It doesn't crash for me (after reinstalling deps) what output do you get?

**Comment by dominictarr** [comment]
it does look a bit half finished though...
I think it should probably attach a reader to the testSource streams and check that they are aborted when you do `rpc.close(true)`

**Comment by pfraze** [comment]
Hm, I reinstalled node modules and got the same error. Here's the `npm ls --depth 0`:

```
secret-stack@2.0.6 /Users/paulfrazee/secret-stack
├── hoox@0.0.1
├── map-merge@1.1.0
├── muxrpc@6.1.2
├── non-private-ip@1.3.0
├── pull-inactivity@2.1.1
├── pull-pushable@1.1.4
├── pull-stream@2.27.0
├── secret-handshake@0.3.4
├── stream-to-pull-stream@1.6.6
└── tape@4.2.0
```

If I remove this line, the error doesn't occur: https://github.com/ssbc/secret-stack/blob/40fc609fc8e980b52229f6707a9058617b5b5c2f/test/close.js#L52
Likewise, if I add `return pull.values([1,2,3])` to this line, the error doesn't occur: https://github.com/ssbc/secret-stack/blob/40fc609fc8e980b52229f6707a9058617b5b5c2f/test/close.js#L33

**Comment by pfraze** [comment]
Here's the stack trace:

```
/Users/paulfrazee/secret-stack/node_modules/pull-stream/sinks.js:7
      read(null, function (end, data) {
      ^
TypeError: read is not a function
    at next (/Users/paulfrazee/secret-stack/node_modules/pull-stream/sinks.js:7:7)
    at exports.drain (/Users/paulfrazee/secret-stack/node_modules/pull-stream/sinks.js:28:5)
    at s (/Users/paulfrazee/secret-stack/node_modules/pull-stream/node_modules/pull-core/index.js:87:27)
    at sink (/Users/paulfrazee/secret-stack/node_modules/muxrpc/pull-weird.js:60:7)
    at PacketStreamSubstream.stream.read (/Users/paulfrazee/secret-stack/node_modules/muxrpc/index.js:132:15)
    at PacketStream._onstream (/Users/paulfrazee/secret-stack/node_modules/muxrpc/node_modules/packet-stream/index.js:218:11)
    at PacketStream.write (/Users/paulfrazee/secret-stack/node_modules/muxrpc/node_modules/packet-stream/index.js:123:41)
    at /Users/paulfrazee/secret-stack/node_modules/muxrpc/pull-weird.js:55:15
    at /Users/paulfrazee/secret-stack/node_modules/pull-stream/sinks.js:15:33
    at /Users/paulfrazee/secret-stack/node_modules/pull-stream/throughs.js:97:9
```

**Comment by dominictarr** [comment]
what npm version are you on?

**Comment by dominictarr** [comment]
and what node version? can you post the entire npm ls?

**Comment by pfraze** [comment]
Node v2.3.0, npm v2.11.1. Npm ls:

```
secret-stack@2.0.6 /Users/paulfrazee/secret-stack
├── hoox@0.0.1
├── map-merge@1.1.0
├─┬ muxrpc@6.1.2
│ ├── packet-stream@2.0.0
│ ├─┬ packet-stream-codec@1.1.0
│ │ ├── pull-reader@1.1.2
│ │ └─┬ pull-through@1.0.17
│ │   └── looper@3.0.0
│ └── pull-goodbye@0.0.1
├─┬ non-private-ip@1.3.0
│ └── ip@0.3.3
├─┬ pull-inactivity@2.1.1
│ ├── pull-abortable@4.0.0
│ └─┬ pull-stream@2.26.1
│   └── pull-core@1.1.0
├─┬ pull-pushable@1.1.4
│ └─┬ pull-stream@2.18.3
│   └── pull-core@1.0.0
├─┬ pull-stream@2.27.0
│ └── pull-core@1.1.0
├─┬ secret-handshake@0.3.4
│ ├─┬ chloride@1.0.20-1
│ │ └── nan@1.9.0
│ ├── deep-equal@1.0.1
│ ├─┬ pull-box-stream@1.0.6
│ │ ├── increment-buffer@1.0.0
│ │ ├── pull-reader@1.1.2
│ │ ├─┬ pull-stream@2.27.0
│ │ │ └── pull-core@1.1.0
│ │ ├─┬ pull-through@1.0.17
│ │ │ └── looper@3.0.0
│ │ └── split-buffer@1.0.0
│ ├─┬ pull-cat@1.1.8
│ │ └── pull-core@1.0.0
│ ├── pull-defer@0.2.0
│ ├─┬ pull-handshake@1.0.4
│ │ ├── pull-delayed-sink@1.0.0
│ │ ├── pull-reader@1.1.2
│ │ └─┬ pull-stream@2.21.0
│ │   └── pull-core@1.0.0
│ ├── pull-pair@1.0.0
│ └─┬ pull-stream@2.26.1
│   └── pull-core@1.1.0
├─┬ stream-to-pull-stream@1.6.6
│ └── pull-core@1.0.0
└─┬ tape@4.2.0
  ├── deep-equal@1.0.1
  ├── defined@0.0.0
  ├── function-bind@1.0.2
  ├─┬ glob@5.0.14
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├─┬ minimatch@2.0.10
  │ │ └─┬ brace-expansion@1.1.0
  │ │   ├── balanced-match@0.2.0
  │ │   └── concat-map@0.0.1
  │ ├─┬ once@1.3.2
  │ │ └── wrappy@1.0.1
  │ └── path-is-absolute@1.0.0
  ├── has@1.0.1
  ├── inherits@2.0.1
  ├── object-inspect@1.0.2
  ├── resumer@0.0.0
  └── through@2.3.8
```

Should I be using npm 3?

**Comment by dominictarr** [comment]
I'm on npm@3.3.1

**Comment by pfraze** [comment]
what version of node are you using? I've always just gotten npm via whatever node packages

**Comment by dominictarr** [comment]
I'm using iojs-v2.5.0 (because that works with sodium) and just reinstalled (npm@2.13.2) and it worked.
trying with 2.3.0...

**Comment by dominictarr** [comment]
okay it still works for me with 2.3.0 too!?

**Comment by dominictarr** [comment]
hmm, maybe this is a race condition then or something else then?

**Comment by pfraze** [comment]
Yeah sounds like it could be a race
