### ISSUE TITLE
tests failing? 

### ISSUE THREAD

**Issue by jedahan** [ssbc/secret-stack#34]
I have started updating my pull request off of master #24 and noticed that the tests are failing for the master branch. I just wanted to check that its a problem with the current checkout and not my local machine.

**Comment by jedahan** [comment]
```
Listening on false:57496 (multiserver net plugin)
/Volumes/data/code/secret-stack/node_modules/pull-stream/sinks/drain.js:16
          read(null, function (end, data) {
          ^

TypeError: read is not a function
    at next (/Volumes/data/code/secret-stack/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/Volumes/data/code/secret-stack/node_modules/pull-stream/sinks/drain.js:37:9)
    at sink (/Volumes/data/code/secret-stack/node_modules/muxrpc/pull-weird.js:61:7)
    at Object.exports.pipeToStream (/Volumes/data/code/secret-stack/node_modules/muxrpc/util.js:138:5)
    at PacketStreamSubstream.stream.read (/Volumes/data/code/secret-stack/node_modules/muxrpc/stream.js:76:18)
    at PacketStream._onstream (/Volumes/data/code/secret-stack/node_modules/packet-stream/index.js:228:11)
    at PacketStream.write (/Volumes/data/code/secret-stack/node_modules/packet-stream/index.js:135:41)
    at /Volumes/data/code/secret-stack/node_modules/muxrpc/pull-weird.js:56:15
    at /Volumes/data/code/secret-stack/node_modules/pull-stream/sinks/drain.js:24:37
    at /Volumes/data/code/secret-stack/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
```

**Comment by dominictarr** [comment]
are you saying tests are failing for https://github.com/ssbc/ssb-server/pull/617
do you do a fresh `rm -rf node_modules && npm install`?
