### ISSUE TITLE
core getAddress providing useless addresses in ipv6 context

### ISSUE THREAD

**Issue by mixmix** [ssbc/secret-stack#46]
both `ssb-local` and `ssb-lan` call : 

```js
sbot.getAddress('private') || sbot.getAddress('local')
```
to determine the "address" to broadcast over UDP. Sadly on my network this looks like : 

```
"net::::8008~shs:m8mRDqHKabyYaoGtDzR1sDIcx8vLfBQC9Mn1bJNywmw="
```

that's an IPv6 address for "localhost" I think ... so peers on the wifi go ahead and try to connect to a feedId from elsewhere ... on the same machine?

I think that's what's producing a screed of these errors : 

```
server error, from net:::1:54810~shs:
Error: shs.server: client hello invalid (phase 3). they dailed a wrong number - they didn't have our public key
    at abort (/home/mix/projects/SSBC/whakapapa-ora/node_modules/secret-handshake/protocol.js:82:45)
    at Object.cb (/home/mix/projects/SSBC/whakapapa-ora/node_modules/secret-handshake/protocol.js:96:20)
    at drain (/home/mix/projects/SSBC/whakapapa-ora/node_modules/pull-reader/index.js:39:14)
    at more (/home/mix/projects/SSBC/whakapapa-ora/node_modules/pull-reader/index.js:55:13)
    at /home/mix/projects/SSBC/whakapapa-ora/node_modules/pull-reader/index.js:66:9
    at /home/mix/projects/SSBC/whakapapa-ora/node_modules/pull-reader/index.js:20:7
    at drain (/home/mix/projects/SSBC/whakapapa-ora/node_modules/stream-to-pull-stream/index.js:126:18)
    at Socket.<anonymous> (/home/mix/projects/SSBC/whakapapa-ora/node_modules/stream-to-pull-stream/index.js:135:5)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)

```

**Comment by mixmix** [comment]
hmmm ... seems like this host address might be coming in from `ssb-config` ... have tracked it down to `non-private-ip`
